# Generated by Django 5.2.4 on 2025-09-10 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('crime_type', models.CharField(choices=[('theft', 'Theft'), ('assault', 'Assault'), ('robbery', 'Robbery'), ('rape', 'Rape'), ('fraud', 'Fraud'), ('other', 'Other')], default='other', max_length=50)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('lga', models.CharField(blank=True, max_length=150, verbose_name='Location / LGA')),
                ('location_description', models.TextField(blank=True)),
                ('incident_description', models.TextField()),
                ('security_agency', models.CharField(blank=True, max_length=150)),
                ('progress_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('closed', 'Closed')], default='new', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
