# Generated by Django 5.2.4 on 2025-09-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='progress_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
