# Generated by Django 5.2.4 on 2025-09-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_progress_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='progress_notes',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
