# Generated by Django 5.2.4 on 2025-10-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_progress_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('new', 'Under Review'), ('reviewed', 'Reviewed')], default='new', max_length=20),
        ),
    ]
